### ISSUE TITLE
Fix Framerate issue from Frontend image communication

### ISSUE THREAD

**Issue by kaitlin31415** [kaitlin31415/BCI4KidsMediapipe#142]
The bug occurs when too many images fill the queue and attempt to be sent at once, it overfills the size of packet that can be sent over the websocket. 

Investigate the bug and implement a fix which only sends a capped framerate.

**Comment by kaitlin31415** [comment]
Here is a sample of the error that occurs with the framerate: 
```

Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/websockets/legacy/server.py", line 231, in handler
await self.ws_handler(self)
File "/c/Users/rajai/Documents/BCI_Test/BCI4KidsMediapipe/Python-Websocket-Test/basicEchoWebsocket.py", line 7, in echo
async for message in websocket:
File "/usr/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 481, in aiter
yield await self.recv()
File "/usr/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 552, in recv
await self.ensure_open()
File "/usr/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
raise self.connection_closed_exc()websockets.exceptions.ConnectionClosedError: sent 1009 (message too big); no close frame received
```

**Comment by Noah-Giustini** [comment]
might be useful if we decide to compress the image: 
https://stackoverflow.com/questions/14672746/how-to-compress-an-image-via-javascript-in-the-browser
